---
name: Check
on: push

jobs:
  build:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.19.5"
      - run: go test -v ./...
      - run: go build ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1
      - uses: github/super-linter@v4.10.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
